stdlist=[
    [
        'sujal',
        'KE',
        'male',
        '12-12-2007',
        '0'
        ],
    [
        'Vishu',
        'MP',
        'male',
        '10-10-2007',
        '0'
        ],    
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],

    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ],
    [
        'kripa',
        'Sa',
        'female',
        '12-11-2006',
        '0'
        ]
]
